spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/G118?currentSchema=security
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080

chaser:
  manager: http://localhost:8005/api/items
